apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sports-store-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: ghcr.io/grafana-community/helm-charts
      chart: loki
      targetRevision: 18.5.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/logging/loki-values.yaml
    - repoURL: https://github.com/sports-store-devops-team/sports-store-deployments.git
      targetRevision: NivBranch
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
