apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sports-store
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=324621154117.dkr.ecr.eu-central-1.amazonaws.com/sports-store-frontend,auth=324621154117.dkr.ecr.eu-central-1.amazonaws.com/sports-store-auth-service,catalog=324621154117.dkr.ecr.eu-central-1.amazonaws.com/sports-store-catalog-service,cart=324621154117.dkr.ecr.eu-central-1.amazonaws.com/sports-store-cart-service,order=324621154117.dkr.ecr.eu-central-1.amazonaws.com/sports-store-order-service,payment=324621154117.dkr.ecr.eu-central-1.amazonaws.com/sports-store-payment-service,gateway=324621154117.dkr.ecr.eu-central-1.amazonaws.com/sports-store-gateway
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag
    argocd-image-updater.argoproj.io/gateway.helm.image-name: gateway.image.repository
    argocd-image-updater.argoproj.io/gateway.helm.image-tag: gateway.image.tag
    argocd-image-updater.argoproj.io/auth.helm.image-name: services.auth.image.repository
    argocd-image-updater.argoproj.io/auth.helm.image-tag: services.auth.image.tag
    argocd-image-updater.argoproj.io/catalog.helm.image-name: services.catalog.image.repository
    argocd-image-updater.argoproj.io/catalog.helm.image-tag: services.catalog.image.tag
    argocd-image-updater.argoproj.io/cart.helm.image-name: services.cart.image.repository
    argocd-image-updater.argoproj.io/cart.helm.image-tag: services.cart.image.tag
    argocd-image-updater.argoproj.io/order.helm.image-name: services.order.image.repository
    argocd-image-updater.argoproj.io/order.helm.image-tag: services.order.image.tag
    argocd-image-updater.argoproj.io/payment.helm.image-name: services.payment.image.repository
    argocd-image-updater.argoproj.io/payment.helm.image-tag: services.payment.image.tag
spec:
  project: default
  source:
    repoURL: 'https://github.com/sports-store-devops-team/sports-store-deployments.git'
    path: helm/sports-store
    targetRevision: YuvalBranch
    helm:
      valueFiles:
        - values.yaml
        - values-aws.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
