apiVersion: v1
kind: ConfigMap

metadata:
  name: order-config
  namespace: sports-store

data:
  CART_URL: "http://cart-service:8003"
  CATALOG_URL: "http://catalog-service:8002"
  PAYMENT_URL: "http://payment-service:8005"
  HTTP_TIMEOUT_SECONDS: "5"
  SHIPPING_FLAT_RATE: "5.00"
  FREE_SHIPPING_THRESHOLD: "100"
