apiVersion: v1
kind: Service

metadata:
  name: cart-service
  namespace: sports-store
  labels:
    app: cart-service

spec:
  selector:
    app: cart-service

  ports:
  - name: http
    protocol: TCP
    port: 8003
    targetPort: 8003
