# Replace this placeholder with the ECR registry for the target AWS account.
global:
  applicationImageRegistry: AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com

backendDefaults:
  imagePullPolicy: IfNotPresent

services:
  auth:
    image:
      repository: sports-store-auth-service
      tag: 0.1.0-abcdef0 # Replace with <semver>-<7-char-git-hash>.
  catalog:
    image:
      repository: sports-store-catalog-service
      tag: 0.1.0-abcdef0 # Replace with <semver>-<7-char-git-hash>.
  cart:
    image:
      repository: sports-store-cart-service
      tag: 0.1.0-abcdef0 # Replace with <semver>-<7-char-git-hash>.
  order:
    image:
      repository: sports-store-order-service
      tag: 0.1.0-abcdef0 # Replace with <semver>-<7-char-git-hash>.
  payment:
    image:
      repository: sports-store-payment-service
      tag: 0.1.0-abcdef0 # Replace with <semver>-<7-char-git-hash>.

frontend:
  image:
    repository: sports-store-frontend
    tag: 0.1.0-abcdef0 # Replace with <semver>-<7-char-git-hash>.
  imagePullPolicy: IfNotPresent

gateway:
  image:
    repository: sports-store-gateway
    tag: 0.2.0-abcdef0 # Replace with <semver>-<7-char-git-hash>.
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

storageClass:
  enabled: true
  name: ebs-sc
  provisioner: ebs.csi.aws.com
  type: gp3
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Retain
  allowVolumeExpansion: true

mongodb:
  persistence:
    storageClass: ebs-sc
