apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-service
  namespace: sports-store
  labels:
    app: catalog-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-service

  template:
    metadata:
      labels:
        app: catalog-service

    spec:
      containers:
      - name: catalog-service
        image: sports-store/catalog-service:0.1.0
        imagePullPolicy: Never

        ports:
        - name: http
          containerPort: 8002
          protocol: TCP

        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CATALOG_MONGO_URI

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET

        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 6

        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
